CREATE DATABASE IF NOT EXISTS Archive;
CREATE DATABASE IF NOT EXISTS patientInfo;
CREATE DATABASE IF NOT EXISTS employeement;
CREATE DATABASE IF NOT EXISTS patientRegistration;
CREATE DATABASE IF NOT EXISTS hospitalManagementSystem;


